### ISSUE TITLE
Make post viewing page

### ISSUE THREAD

**Issue by Sean-Meyers** [Sean-Meyers/CMPUT404-project-socialdistribution#7]
- Body
- Comments

**Comment by ildebr** [comment]
Is this issue still available?

**Comment by Sean-Meyers** [comment]
@ildebr This is a project for a university assignment, so it is not open to collaboration from people outside of our assignment groups. If you are looking for an open source project like this to work on, you could probably find a completed version of this assignment from a previous term by browsing other forks of the upstream. You could then fork one of those yourself and then make your own changes if you want. They should all have open source licenses of some form as far as I know.
